algo: PPOLag
env_id: SafetyPointGoal1-v0
train_cfgs:
  # 1e6 for simplicity
  total_steps: 1000000 
  vector_env_nums: 1
logger_cfgs:
  use_wandb: false
algo_cfgs:
  steps_per_epoch: 30000
  update_iters: 50
  gamma: 0.99
  cost_gamma: 0.99
  lam: 0.97
  lam_c: 0.97
  clip: 0.2
  target_kl: 0.01
  entropy_coef: 0.0
  update_iters: 80
lagrange_cfgs: 
  cost_limit: 25.0
  lagrangian_multiplier_init: 1.0
  lambda_lr: 5e-2
model_cfgs: 
  actor: {
    lr: 3e-4,
    hidden_sizes: [256,256],
    activation: "tanh",
  }
  critic: {
    lr: 1e-3,
    hidden_sizes: [256,256],
    activation: "tanh",
  }
